kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-deployment
  namespace: mlcode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-pod
  template:
    metadata:
      labels:
        app: kafka-pod
    spec:
      containers:
        - name: kafka
          image: apache/kafka:latest
          envFrom:
          - configMapRef:
              name: mlcode-config
          ports:
            - containerPort: 9092
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-data
          emptyDir: {}
