kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio-deployment
  namespace: mlcode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-pod
  template:
    metadata:
      labels:
        app: minio-pod
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
            - "--console-address=:9090"
          envFrom:
          - configMapRef:
              name: mlcode-config
          ports:
            - containerPort: 9000
            - containerPort: 9090
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          emptyDir: {}
