kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  namespace: mlcode
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-storage
  hostPath:
    path: /mnt/data/redis
    type: DirectoryOrCreate
    
